//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var image: image { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }

  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func validate() throws {

  }


  /// This `_R.image` struct is generated, and contains static references to 7 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `resume`.
    var resume: RswiftResources.ImageResource { .init(name: "resume", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `suspend`.
    var suspend: RswiftResources.ImageResource { .init(name: "suspend", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `かざまくん`.
    var かざまくん: RswiftResources.ImageResource { .init(name: "かざまくん", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `しんのすけ`.
    var しんのすけ: RswiftResources.ImageResource { .init(name: "しんのすけ", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `まさおくん`.
    var まさおくん: RswiftResources.ImageResource { .init(name: "まさおくん", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ネネちゃん`.
    var ネネちゃん: RswiftResources.ImageResource { .init(name: "ネネちゃん", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ボーちゃん`.
    var ボーちゃん: RswiftResources.ImageResource { .init(name: "ボーちゃん", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.file` struct is generated, and contains static references to 1 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `Sport.json`.
    var sportJson: RswiftResources.FileResource { .init(name: "Sport", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }
  }
}